language: python
sudo: false
python:
 - "2.6"
 - "2.7"
 - "3.3"
 - "3.4"
env:
  matrix:
   - DJANGO=Django==1.11
   - DJANGO=Django==2.0
install:
 - pip install $DJANGO --use-mirrors
 - pip install . --use-mirrors
 - pip install coverage
branches:
 only:
  - master
  - develop
script: coverage run --source=django_faker setup.py test
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=Django==2.0
    - python: "2.6"
      env: DJANGO=Django==2.0
    - python: "2.7"
      env: DJANGO=Django==2.0
    - python: "2.7"
      env: DJANGO=Django==2.0
    - python: "3.3"
      env: DJANGO=Django==1.11
    - python: "3.3"
      env: DJANGO=Django==1.11
    - python: "3.4"
      env: DJANGO=Django==1.11
    - python: "3.4"
      env: DJANGO=Django==1.11
after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls
